### model
model_name_or_path: /content/GLM-OCR
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.1
use_rslora: true
lora_target: all
freeze_vision_tower: true
freeze_multi_modal_projector: false

### dataset
dataset: vietnamese_ocr
eval_dataset: vietnamese_ocr_val
template: glm_ocr
cutoff_len: 2048
preprocessing_num_workers: 8
dataloader_num_workers: 2
eval_strategy: steps
eval_steps: 200
load_best_model_at_end: true
metric_for_best_model: eval_loss
early_stopping_patience: 3
per_device_eval_batch_size: 1

### output
output_dir: "/content/drive/My Drive/ocr_data/glm-ocr-vn-checkpoints"
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3
lr_scheduler_type: constant_with_warmup
warmup_ratio: 0.05
fp16: true
